import Head from "next/head";
//import Image from 'next/image'
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Conversion from "../components/Conversion";
import CelsiusInput from "../components/CelsiusInput";
import FarenheitInput from "../components/FarenheitInput";

export default function Home() {
  const [farenheit, setFarenheit] = useState({
    temp: 0,
    scale: "f",
  });
  const [celsius, setCelsius] = useState({
    temp: 0,
    scale: "c",
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1 style={{ color: "red" }}>Temperature Converter</h1>
      </section>
      <main className={styles.main}>
        <div className={styles.left}>
          <FarenheitInput farenheit={farenheit} setFarenheit={setFarenheit} />
        </div>
        <div className={styles.right}>
          <CelsiusInput celsius={celsius} setCelsius={setCelsius} />
        </div>
        <Conversion farenheit={farenheit} celsius={celsius} />
      </main>
    </div>
  );
}
